name: gocart
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2
  flutter_svg: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

fonts:
  - family: Sora
    fonts:
      - asset: assets/fonts/Sora-Bold.ttf
        weight: 700
      - asset: assets/fonts/Sora-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Sora-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Sora-Light.ttf
        weight: 300
      - asset: assets/fonts/Sora-Medium.ttf
        weight: 500
      - asset: assets/fonts/Sora-Regular.ttf
        weight: 400
      - asset: assets/fonts/Sora-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Sora-Thin.ttf
        weight: 100

